language: python
python:
- "3.6"

before_install:
  # Install FEniCS (but don't do an 'apt-get upgrade' as this will timeout the process)
  - sudo add-apt-repository ppa:fenics-packages/fenics -y
  - sudo apt-get update -q
  - sudo apt-get install fenics -y

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - rm miniconda.sh
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda update -q --all
    - conda install numpy>=1.12.0
    - conda install pytest>=3.2.0
    - conda install pytest-cov
    - conda install matplotlib
    - conda config --append channels conda-forge
    - conda env create -qf test-environment.yaml;
    - source activate fenicsproject;
script:
    - pytest -vv --cov=./;
